/**
 * Models barrel export - All Classifications entities
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./classification-proposal.entity.js";
export * from "./knowledge-annotation.entity.js";
