/**
 * ClassificationProposal Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ClassificationProposalEntity } from "@phytoseal/core/classifications/models/index.js";
import { classificationsSchemas } from "@phytoseal/core/classifications";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cls";

export function createClassificationProposal(overrides: Partial<ClassificationProposalEntity> = {}) {
  const raw = {
    id: overrides.id ?? `cls_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    materialDescription: overrides.materialDescription ?? faker.lorem.sentence(),
    status: overrides.status ?? "proposed",
    ...overrides,
  };

  return classificationsSchemas.ClassificationProposal.parse(raw);
}

export function classificationProposalBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createClassificationProposal(overrides));
}
