/**
 * CreateReview DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { BrokerReview } from "@phytoseal/core/classifications";
import { classificationsSchemas } from "@phytoseal/core/classifications";

export function createCreateReviewRequest(overrides: Partial<BrokerReview> = {}) {
  const raw = {
    outcome: overrides.outcome ?? "approved",
    ...overrides,
  };

  return classificationsSchemas.BrokerReview.parse(raw);
}
