/**
 * EvidencePacks DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvidencePacks Domain Module - Composition root
 *
 * DDD: Composition root for evidence-packs domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EvidencePackRepositoryAdapter,
} from "@phytoseal/adapters/evidence-packs";
import { getIdGeneratorService } from "@phytoseal/adapters";
import type { AdapterDynamoDBClient } from "@phytoseal/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateEvidencePack,
  ExecuteGetEvidencePack,
  ExecuteListEvidencePacks,
} from "@phytoseal/services/evidence-packs/usecases";
// Ports (interfaces)
import type {
  EvidencePackRepository,
} from "@phytoseal/services/evidence-packs/ports";

export interface EvidencePacksDomainModule {
  repos: {
    evidencePacks: EvidencePackRepository;
  };
  useCases: {
    evidencePacks: {
      create: ExecuteCreateEvidencePack;
      get: ExecuteGetEvidencePack;
      list: ExecuteListEvidencePacks;
    };
  };
}

export function buildEvidencePacksDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): EvidencePacksDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      evidencePacks?: EvidencePackRepository;
    } = {};

    obj.evidencePacks = new EvidencePackRepositoryAdapter(dynamoClient);
    return {
      evidencePacks: obj.evidencePacks!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    evidencePacks: {
      create: new ExecuteCreateEvidencePack(executionContext, idGenerator, repos.evidencePacks),
      get: new ExecuteGetEvidencePack(executionContext, idGenerator, repos.evidencePacks),
      list: new ExecuteListEvidencePacks(executionContext, idGenerator, repos.evidencePacks),
    },
  };
  return { repos, useCases: useCases as EvidencePacksDomainModule["useCases"] };
}
