/**
 * CycleTimeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CycleTimeRepository Port
 *
 * DDD: Application port for cycletimerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCycleTimeMetricsInput, GetCycleTimeMetricsOutput } from "../dto/cycle-time.dto";
export interface CycleTimeRepository {
  getCycleTimeMetrics(input: GetCycleTimeMetricsInput): Promise<GetCycleTimeMetricsOutput>;
}

export type { GetCycleTimeMetricsInput, GetCycleTimeMetricsOutput } from "../dto/cycle-time.dto";
