/**
 * ReportRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReportRepository Port
 *
 * DDD: Application port for reportrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateCycleTimeReportInput, CreateCycleTimeReportOutput, GetCycleTimeReportInput, GetCycleTimeReportOutput, ListCycleTimeReportsInput, ListCycleTimeReportsOutput } from "../dto/report.dto";
export interface ReportRepository {
  listCycleTimeReports(input: ListCycleTimeReportsInput): Promise<ListCycleTimeReportsOutput>;
  createCycleTimeReport(input: CreateCycleTimeReportInput): Promise<CreateCycleTimeReportOutput>;
  getCycleTimeReport(input: GetCycleTimeReportInput): Promise<GetCycleTimeReportOutput>;
}

export type { CreateCycleTimeReportInput, CreateCycleTimeReportOutput, GetCycleTimeReportInput, GetCycleTimeReportOutput, ListCycleTimeReportsInput, ListCycleTimeReportsOutput } from "../dto/report.dto";
