/**
 * Routes for Present
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { presentCertificate } from "../handlers/present.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { CertificatePresentRequest } from "@phytoseal/core/certificates/types";

// Fastify types are available globally
export async function presentRoutes(fastify: FastifyInstance) {
  // POST /v1/certificates/{certificateId}/present (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/certificates/:certificateId/present",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { certificateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: CertificatePresentRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCertificatesDependenciesForRequest();
        await presentCertificate(request, reply, deps);
      });
    }
  );


}
