/**
 * CreateDisclosurePolicy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createDisclosurePolicy } from "@phytoseal/api-server/domains/port-parties/handlers";
import type { PortPartiesDDDDependencies } from "@phytoseal/api-server/domains/port-parties";
import { createDisclosurePolicy as createDisclosurePolicyEntity } from "@phytoseal/factories/port-parties";
import { createCreateDisclosurePolicyRequest } from "@phytoseal/factories/port-parties";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@phytoseal/tests/shared";
import { PORTPARTIES_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateDisclosurePolicy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PortPartiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PortPartiesDDDDependencies>(
      PORTPARTIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateDisclosurePolicyRequest();
    const entity = createDisclosurePolicyEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateDisclosurePolicy, "execute").mockResolvedValue(useCaseResult);

    await createDisclosurePolicy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateDisclosurePolicy.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
