/**
 * GetDisclosurePolicy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDisclosurePolicy } from "@phytoseal/api-server/domains/port-parties/handlers";
import type { PortPartiesDDDDependencies } from "@phytoseal/api-server/domains/port-parties";
import { createDisclosurePolicy as createDisclosurePolicyEntity } from "@phytoseal/factories/port-parties";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@phytoseal/tests/shared";
import { PORTPARTIES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDisclosurePolicy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PortPartiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PortPartiesDDDDependencies>(
      PORTPARTIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createDisclosurePolicyEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDisclosurePolicy, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { policyId: entity.id };

    await getDisclosurePolicy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDisclosurePolicy.execute).toHaveBeenCalledWith(expect.objectContaining({ policyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { policyId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDisclosurePolicy, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDisclosurePolicy(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
