/**
 * ListDisclosurePolicies handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listDisclosurePolicies } from "@phytoseal/api-server/domains/port-parties/handlers";
import type { PortPartiesDDDDependencies } from "@phytoseal/api-server/domains/port-parties";
import { createDisclosurePolicy as createDisclosurePolicyEntity } from "@phytoseal/factories/port-parties";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@phytoseal/tests/shared";
import { PORTPARTIES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListDisclosurePolicies", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PortPartiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PortPartiesDDDDependencies>(
      PORTPARTIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createDisclosurePolicyEntity({ orgId }),
      createDisclosurePolicyEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListDisclosurePolicies, "execute").mockResolvedValue(useCaseResult);

    await listDisclosurePolicies(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListDisclosurePolicies.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
