/**
 * CreateClassificationProposal handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createClassificationProposal } from "@phytoseal/api-server/domains/classifications/handlers";
import type { ClassificationsDDDDependencies } from "@phytoseal/api-server/domains/classifications";
import { createClassificationProposal as createClassificationProposalEntity } from "@phytoseal/factories/classifications";
import { createCreateClassificationProposalRequest } from "@phytoseal/factories/classifications";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@phytoseal/tests/shared";
import { CLASSIFICATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateClassificationProposal", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ClassificationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ClassificationsDDDDependencies>(
      CLASSIFICATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateClassificationProposalRequest();
    const entity = createClassificationProposalEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateClassificationProposal, "execute").mockResolvedValue(useCaseResult);

    await createClassificationProposal(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateClassificationProposal.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
