/**
 * ListClassificationProposals handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listClassificationProposals } from "@phytoseal/api-server/domains/classifications/handlers";
import type { ClassificationsDDDDependencies } from "@phytoseal/api-server/domains/classifications";
import { createClassificationProposal as createClassificationProposalEntity } from "@phytoseal/factories/classifications";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@phytoseal/tests/shared";
import { CLASSIFICATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListClassificationProposals", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ClassificationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ClassificationsDDDDependencies>(
      CLASSIFICATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createClassificationProposalEntity({ orgId }),
      createClassificationProposalEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListClassificationProposals, "execute").mockResolvedValue(useCaseResult);

    await listClassificationProposals(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListClassificationProposals.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
