/**
 * Certificates DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Certificates Domain Module - Composition root
 *
 * DDD: Composition root for certificates domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CertificateRepositoryAdapter,
  DecisionRepositoryAdapter,
  EventRepositoryAdapter,
  PresentRepositoryAdapter,
} from "@phytoseal/adapters/certificates";
import { getIdGeneratorService } from "@phytoseal/adapters";
import type { AdapterDynamoDBClient } from "@phytoseal/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateCertificate,
  ExecuteDecideCertificate,
  ExecuteGetCertificate,
  ExecuteListCertificateEvents,
  ExecuteListCertificates,
  ExecutePresentCertificate,
} from "@phytoseal/services/certificates/usecases";
// Ports (interfaces)
import type {
  CertificateRepository,
  DecisionRepository,
  EventRepository,
  PresentRepository,
} from "@phytoseal/services/certificates/ports";

export interface CertificatesDomainModule {
  repos: {
    certificates: CertificateRepository;
    decisions: DecisionRepository;
    events: EventRepository;
    presents: PresentRepository;
  };
  useCases: {
    certificates: {
      create: ExecuteCreateCertificate;
      get: ExecuteGetCertificate;
      list: ExecuteListCertificates;
    };
    decisions: {
      get: ExecuteDecideCertificate;
    };
    events: {
      list: ExecuteListCertificateEvents;
    };
    presents: {
      get: ExecutePresentCertificate;
    };
  };
}

export function buildCertificatesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CertificatesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      certificates?: CertificateRepository;
      decisions?: DecisionRepository;
      events?: EventRepository;
      presents?: PresentRepository;
    } = {};

    obj.certificates = new CertificateRepositoryAdapter(dynamoClient);
    obj.decisions = new DecisionRepositoryAdapter(dynamoClient);
    obj.events = new EventRepositoryAdapter(dynamoClient);
    obj.presents = new PresentRepositoryAdapter(dynamoClient);
    return {
      certificates: obj.certificates!,
      decisions: obj.decisions!,
      events: obj.events!,
      presents: obj.presents!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    certificates: {
      create: new ExecuteCreateCertificate(executionContext, idGenerator, repos.certificates),
      get: new ExecuteGetCertificate(executionContext, idGenerator, repos.certificates),
      list: new ExecuteListCertificates(executionContext, idGenerator, repos.certificates),
    },
    decisions: {
      get: new ExecuteDecideCertificate(executionContext, idGenerator, repos.decisions),
    },
    events: {
      list: new ExecuteListCertificateEvents(executionContext, idGenerator, repos.events),
    },
    presents: {
      get: new ExecutePresentCertificate(executionContext, idGenerator, repos.presents),
    },
  };
  return { repos, useCases: useCases as CertificatesDomainModule["useCases"] };
}
