/**
 * Routes for ClassificationProposal
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createClassificationProposal, getClassificationProposal, listClassificationProposals } from "../handlers/classification-proposal.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { ClassificationProposalCreateRequest } from "@phytoseal/core/classifications/types";

// Fastify types are available globally
export async function classificationProposalRoutes(fastify: FastifyInstance) {
  // POST /v1/classification-proposals (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/classification-proposals",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: ClassificationProposalCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getClassificationsDependenciesForRequest();
        await createClassificationProposal(request, reply, deps);
      });
    }
  );


  // GET /v1/classification-proposals (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/classification-proposals",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getClassificationsDependenciesForRequest();
        await listClassificationProposals(request, reply, deps);
      });
    }
  );


  // GET /v1/classification-proposals/{proposalId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/classification-proposals/:proposalId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { proposalId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getClassificationsDependenciesForRequest();
        await getClassificationProposal(request, reply, deps);
      });
    }
  );


}
