/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { classificationProposalRoutes } from "./classification-proposal.routes.js";
export { knowledgeAnnotationRoutes } from "./knowledge-annotation.routes.js";
export { reviewRoutes } from "./review.routes.js";
