/**
 * Routes for Review
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { reviewClassificationProposal } from "../handlers/review.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { BrokerReview } from "@phytoseal/core/classifications/types";

// Fastify types are available globally
export async function reviewRoutes(fastify: FastifyInstance) {
  // POST /v1/classification-proposals/{proposalId}/review (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/classification-proposals/:proposalId/review",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { proposalId: string }; Querystring: Record<string, string | string[] | undefined>; Body: BrokerReview }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getClassificationsDependenciesForRequest();
        await reviewClassificationProposal(request, reply, deps);
      });
    }
  );


}
