/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the certificates domain.
 * Use these factories in tests to create test data.
 */

export { createCertificate } from "./certificate/entity/certificate.entity.factory.js";
export { createCreateCertificateRequest } from "./certificate/dto/create-certificate.dto.factory.js";
export { createCreateDecisionRequest } from "./decision/dto/create-decision.dto.factory.js";
export { createCreatePresentRequest } from "./present/dto/create-present.dto.factory.js";
