/**
 * Repository interface for Amendment
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: amendments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AmendmentEntity
} from "../models/amendment.entity.js";
import type {
  ListAmendmentsParams,
  AmendmentCreateRequest
} from "../types/index.js";
/**
 * AmendmentRepository Interface
 */
export interface AmendmentRepository extends CreateReadRepository<AmendmentEntity, AmendmentCreateRequest, string, ListAmendmentsParams> {

}
