/**
 * Repository interface for LegalHold
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  LegalHoldEntity
} from "../models/legal-hold.entity.js";
import type {
  ListLegalHoldsParams,
  LegalHoldCreateRequest
} from "../types/index.js";
/**
 * LegalHoldRepository Interface
 */
export interface LegalHoldRepository extends CreateReadRepository<LegalHoldEntity, LegalHoldCreateRequest, string, ListLegalHoldsParams> {

}
