/**
 * ExecuteCreateLegalHold - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateLegalHold Use Case
 *
 * DDD: Application use case for create LegalHold.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateLegalHoldInput, CreateLegalHoldOutput } from "../dto/legal-hold.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { LegalHoldRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateLegalHold {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly legalHold: LegalHoldRepository
  ) {}

  async execute(input: CreateLegalHoldInput): Promise<CreateLegalHoldOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.hldId();

    // All field names extracted from OpenAPI spec: affectedCertificateIds, jurisdiction, rationale
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.jurisdiction) {
      throw new ValidationError("jurisdiction is required");
    }
    if (!input.rationale) {
      throw new ValidationError("rationale is required");
    }
    if (!input.affectedCertificateIds) {
      throw new ValidationError("affectedCertificateIds is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (legal-holds domain)
    const entityId = this.idGenerator.hldId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.legalHold.createLegalHold({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateLegalHoldOutput;
  }
}
