/**
 * ExecuteListLegalHolds - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListLegalHolds Use Case
 *
 * DDD: Application use case for list LegalHold.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListLegalHoldsInput, ListLegalHoldsOutput } from "../dto/legal-hold.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { LegalHoldRepository } from "../ports";

export class ExecuteListLegalHolds {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly legalHold: LegalHoldRepository
  ) {}

  async execute(input: ListLegalHoldsInput): Promise<ListLegalHoldsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.hldId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.legalHold.listLegalHolds({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListLegalHoldsOutput;
  }
}
