/**
 * Handlers for ClassificationProposal
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ClassificationsDomainModule } from "../dependencies/classifications-ddd.dependencies.js";
import type { ClassificationProposalCreateRequest } from "@phytoseal/core/classifications/types";
import type { CreateClassificationProposalInput, GetClassificationProposalInput, ListClassificationProposalsInput } from "@phytoseal/services/classifications";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/classification-proposals
 * Operation: listClassificationProposals
 */
export async function listClassificationProposals(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ClassificationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListClassificationProposalsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.classificationProposals.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/classification-proposals
 * Operation: createClassificationProposal
 */
export async function createClassificationProposal(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: ClassificationProposalCreateRequest }>,
  reply: FastifyReply,
  deps: ClassificationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateClassificationProposalInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.classificationProposals.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/classification-proposals/{proposalId}
 * Operation: getClassificationProposal
 */
export async function getClassificationProposal(
  request: FastifyRequest<{ Params: { proposalId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ClassificationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetClassificationProposalInput = {
    proposalId: request.params.proposalId,
  };
  const result = await deps.useCases.classificationProposals.get.execute(input);
  return reply.code(200).send(result);
}


