/**
 * Handlers for KnowledgeAnnotation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ClassificationsDomainModule } from "../dependencies/classifications-ddd.dependencies.js";
import type { KnowledgeAnnotationCreateRequest } from "@phytoseal/core/classifications/types";
import type { CreateKnowledgeAnnotationInput, GetKnowledgeAnnotationInput, ListKnowledgeAnnotationsInput } from "@phytoseal/services/classifications";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/knowledge-annotations
 * Operation: listKnowledgeAnnotations
 */
export async function listKnowledgeAnnotations(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], promotedToPlaybook?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ClassificationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListKnowledgeAnnotationsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.knowledgeAnnotations.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/knowledge-annotations
 * Operation: createKnowledgeAnnotation
 */
export async function createKnowledgeAnnotation(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: KnowledgeAnnotationCreateRequest }>,
  reply: FastifyReply,
  deps: ClassificationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateKnowledgeAnnotationInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.knowledgeAnnotations.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/knowledge-annotations/{annotationId}
 * Operation: getKnowledgeAnnotation
 */
export async function getKnowledgeAnnotation(
  request: FastifyRequest<{ Params: { annotationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ClassificationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetKnowledgeAnnotationInput = {
    annotationId: request.params.annotationId,
  };
  const result = await deps.useCases.knowledgeAnnotations.get.execute(input);
  return reply.code(200).send(result);
}


