/**
 * Handlers for Review
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ClassificationsDomainModule } from "../dependencies/classifications-ddd.dependencies.js";
import type { BrokerReview } from "@phytoseal/core/classifications/types";
import type { ReviewClassificationProposalInput } from "@phytoseal/services/classifications";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/classification-proposals/{proposalId}/review
 * Operation: reviewClassificationProposal
 */
export async function reviewClassificationProposal(
  request: FastifyRequest<{ Params: { proposalId: string }; Querystring: Record<string, string | string[] | undefined>; Body: BrokerReview }>,
  reply: FastifyReply,
  deps: ClassificationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ReviewClassificationProposalInput = {
    proposalId: request.params.proposalId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.reviews.get.execute(input);
  return reply.code(200).send(result);
}


