/**
 * GetKnowledgeAnnotation handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getKnowledgeAnnotation } from "@phytoseal/api-server/domains/classifications/handlers";
import type { ClassificationsDDDDependencies } from "@phytoseal/api-server/domains/classifications";
import { createKnowledgeAnnotation as createKnowledgeAnnotationEntity } from "@phytoseal/factories/classifications";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@phytoseal/tests/shared";
import { CLASSIFICATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetKnowledgeAnnotation", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ClassificationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ClassificationsDDDDependencies>(
      CLASSIFICATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createKnowledgeAnnotationEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetKnowledgeAnnotation, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { annotationId: entity.id };

    await getKnowledgeAnnotation(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetKnowledgeAnnotation.execute).toHaveBeenCalledWith(expect.objectContaining({ annotationId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { annotationId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetKnowledgeAnnotation, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getKnowledgeAnnotation(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
