/**
 * Amendment DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: amendments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Amendment DTOs
 *
 * DDD: Application DTOs for Amendment use cases.
 */

import type { AmendmentCreateRequest, CreateCertificateAmendmentParams, GetAmendmentParams, ListAmendmentsParams } from "@phytoseal/core/amendments/types";

export type ListAmendmentsInput = ListAmendmentsParams;

export type CreateCertificateAmendmentInput = CreateCertificateAmendmentParams & AmendmentCreateRequest;

export type GetAmendmentInput = GetAmendmentParams;

export type ListAmendmentsOutput = {};

export type CreateCertificateAmendmentOutput = {};

export type GetAmendmentOutput = {};
