/**
 * Reject DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: amendments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reject DTOs
 *
 * DDD: Application DTOs for Reject use cases.
 */

import type { AmendmentDecisionRequest, RejectAmendmentParams } from "@phytoseal/core/amendments/types";

export type RejectAmendmentInput = RejectAmendmentParams & AmendmentDecisionRequest;

export type RejectAmendmentOutput = {};
