/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the classifications domain.
 * Use these factories in tests to create test data.
 */

export { createClassificationProposal } from "./classification-proposal/entity/classification-proposal.entity.factory.js";
export { createCreateClassificationProposalRequest } from "./classification-proposal/dto/create-classification-proposal.dto.factory.js";
export { createCreateKnowledgeAnnotationRequest } from "./knowledge-annotation/dto/create-knowledge-annotation.dto.factory.js";
export { createCreateReviewRequest } from "./review/dto/create-review.dto.factory.js";
export { createKnowledgeAnnotation } from "./knowledge-annotation/entity/knowledge-annotation.entity.factory.js";
