/**
 * LegalHoldRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LegalHoldRepository Port
 *
 * DDD: Application port for legalholdrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateLegalHoldInput, CreateLegalHoldOutput, GetLegalHoldInput, GetLegalHoldOutput, ListLegalHoldsInput, ListLegalHoldsOutput } from "../dto/legal-hold.dto";
export interface LegalHoldRepository {
  listLegalHolds(input: ListLegalHoldsInput): Promise<ListLegalHoldsOutput>;
  createLegalHold(input: CreateLegalHoldInput): Promise<CreateLegalHoldOutput>;
  getLegalHold(input: GetLegalHoldInput): Promise<GetLegalHoldOutput>;
}

export type { CreateLegalHoldInput, CreateLegalHoldOutput, GetLegalHoldInput, GetLegalHoldOutput, ListLegalHoldsInput, ListLegalHoldsOutput } from "../dto/legal-hold.dto";
