/**
 * DisclosurePolicyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisclosurePolicyRepository Port
 *
 * DDD: Application port for disclosurepolicyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateDisclosurePolicyInput, CreateDisclosurePolicyOutput, GetDisclosurePolicyInput, GetDisclosurePolicyOutput, ListDisclosurePoliciesInput, ListDisclosurePoliciesOutput, ReplaceDisclosurePolicyInput, ReplaceDisclosurePolicyOutput } from "../dto/disclosure-policy.dto";
export interface DisclosurePolicyRepository {
  listDisclosurePolicies(input: ListDisclosurePoliciesInput): Promise<ListDisclosurePoliciesOutput>;
  createDisclosurePolicy(input: CreateDisclosurePolicyInput): Promise<CreateDisclosurePolicyOutput>;
  getDisclosurePolicy(input: GetDisclosurePolicyInput): Promise<GetDisclosurePolicyOutput>;
  replaceDisclosurePolicy(input: ReplaceDisclosurePolicyInput): Promise<ReplaceDisclosurePolicyOutput>;
}

export type { CreateDisclosurePolicyInput, CreateDisclosurePolicyOutput, GetDisclosurePolicyInput, GetDisclosurePolicyOutput, ListDisclosurePoliciesInput, ListDisclosurePoliciesOutput, ReplaceDisclosurePolicyInput, ReplaceDisclosurePolicyOutput } from "../dto/disclosure-policy.dto";
