/**
 * InviteRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InviteRepository Port
 *
 * DDD: Application port for inviterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { InvitePortPartyInput, InvitePortPartyOutput } from "../dto/invite.dto";
export interface InviteRepository {
  invitePortParty(input: InvitePortPartyInput): Promise<InvitePortPartyOutput>;
}

export type { InvitePortPartyInput, InvitePortPartyOutput } from "../dto/invite.dto";
