/**
 * PortPartyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PortPartyRepository Port
 *
 * DDD: Application port for portpartyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreatePortPartyInput, CreatePortPartyOutput, GetPortPartyInput, GetPortPartyOutput, ListPortPartiesInput, ListPortPartiesOutput, UpdatePortPartyInput, UpdatePortPartyOutput } from "../dto/port-party.dto";
export interface PortPartyRepository {
  listPortParties(input: ListPortPartiesInput): Promise<ListPortPartiesOutput>;
  createPortParty(input: CreatePortPartyInput): Promise<CreatePortPartyOutput>;
  getPortParty(input: GetPortPartyInput): Promise<GetPortPartyOutput>;
  updatePortParty(input: UpdatePortPartyInput): Promise<UpdatePortPartyOutput>;
}

export type { CreatePortPartyInput, CreatePortPartyOutput, GetPortPartyInput, GetPortPartyOutput, ListPortPartiesInput, ListPortPartiesOutput, UpdatePortPartyInput, UpdatePortPartyOutput } from "../dto/port-party.dto";
