/**
 * LegalHold DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LegalHold DTOs
 *
 * DDD: Application DTOs for LegalHold use cases.
 */

import type { GetLegalHoldParams, LegalHoldCreateRequest, ListLegalHoldsParams } from "@phytoseal/core/legal-holds/types";

export type ListLegalHoldsInput = ListLegalHoldsParams;

export type CreateLegalHoldInput = LegalHoldCreateRequest;

export type GetLegalHoldInput = GetLegalHoldParams;

export type ListLegalHoldsOutput = {};

export type CreateLegalHoldOutput = {};

export type GetLegalHoldOutput = {};
