/**
 * CreateDecision DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { CertificateDecisionRequest } from "@phytoseal/core/certificates";
import { certificatesSchemas } from "@phytoseal/core/certificates";

export function createCreateDecisionRequest(overrides: Partial<CertificateDecisionRequest> = {}) {
  const raw = {
    outcome: overrides.outcome ?? "accepted",
    ...overrides,
  };

  return certificatesSchemas.CertificateDecisionRequest.parse(raw);
}
