/**
 * Handlers for Approve
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: amendments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AmendmentsDomainModule } from "../dependencies/amendments-ddd.dependencies.js";
import type { AmendmentDecisionRequest } from "@phytoseal/core/amendments/types";
import type { ApproveAmendmentInput } from "@phytoseal/services/amendments";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/amendments/{amendmentId}/approve
 * Operation: approveAmendment
 */
export async function approveAmendment(
  request: FastifyRequest<{ Params: { amendmentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: AmendmentDecisionRequest }>,
  reply: FastifyReply,
  deps: AmendmentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ApproveAmendmentInput = {
    amendmentId: request.params.amendmentId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.approves.create.execute(input);
  return reply.code(200).send(result);
}


