/**
 * ClassificationProposalRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClassificationProposalRepository Port
 *
 * DDD: Application port for classificationproposalrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateClassificationProposalInput, CreateClassificationProposalOutput, GetClassificationProposalInput, GetClassificationProposalOutput, ListClassificationProposalsInput, ListClassificationProposalsOutput } from "../dto/classification-proposal.dto";
export interface ClassificationProposalRepository {
  listClassificationProposals(input: ListClassificationProposalsInput): Promise<ListClassificationProposalsOutput>;
  createClassificationProposal(input: CreateClassificationProposalInput): Promise<CreateClassificationProposalOutput>;
  getClassificationProposal(input: GetClassificationProposalInput): Promise<GetClassificationProposalOutput>;
}

export type { CreateClassificationProposalInput, CreateClassificationProposalOutput, GetClassificationProposalInput, GetClassificationProposalOutput, ListClassificationProposalsInput, ListClassificationProposalsOutput } from "../dto/classification-proposal.dto";
