/**
 * ReviewRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReviewRepository Port
 *
 * DDD: Application port for reviewrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ReviewClassificationProposalInput, ReviewClassificationProposalOutput } from "../dto/review.dto";
export interface ReviewRepository {
  reviewClassificationProposal(input: ReviewClassificationProposalInput): Promise<ReviewClassificationProposalOutput>;
}

export type { ReviewClassificationProposalInput, ReviewClassificationProposalOutput } from "../dto/review.dto";
