/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as amendmentsRoutes from "../../domains/amendments/routes/index.js";
import * as certificatesRoutes from "../../domains/certificates/routes/index.js";
import * as classificationsRoutes from "../../domains/classifications/routes/index.js";
import * as evidencePacksRoutes from "../../domains/evidence-packs/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as legalHoldsRoutes from "../../domains/legal-holds/routes/index.js";
import * as metricsRoutes from "../../domains/metrics/routes/index.js";
import * as portPartiesRoutes from "../../domains/port-parties/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "amendments", mod: amendmentsRoutes },
  { domain: "certificates", mod: certificatesRoutes },
  { domain: "classifications", mod: classificationsRoutes },
  { domain: "evidence-packs", mod: evidencePacksRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "legal-holds", mod: legalHoldsRoutes },
  { domain: "metrics", mod: metricsRoutes },
  { domain: "port-parties", mod: portPartiesRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
