/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Classifications Domain Use Cases
 * 
 * List of all use case names for the classifications domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CLASSIFICATIONS_USE_CASES = [
  "executeCreateClassificationProposal",
  "executeCreateKnowledgeAnnotation",
  "executeGetClassificationProposal",
  "executeGetKnowledgeAnnotation",
  "executeListClassificationProposals",
  "executeListKnowledgeAnnotations",
  "executeReviewClassificationProposal"
] as const;
