/**
 * CreateDisclosurePolicy DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DisclosurePolicyCreateRequest } from "@phytoseal/core/port-parties";
import { portPartiesSchemas } from "@phytoseal/core/port-parties";

export function createCreateDisclosurePolicyRequest(overrides: Partial<DisclosurePolicyCreateRequest> = {}) {
  const raw = {
    documentClass: overrides.documentClass ?? faker.lorem.word(),
    name: overrides.name ?? faker.person.fullName(),
    rules: overrides.rules ?? [],
    ...overrides,
  };

  return portPartiesSchemas.DisclosurePolicyCreateRequest.parse(raw);
}
