/**
 * ListDisclosurePolicy DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListDisclosurePoliciesParams } from "@phytoseal/core/port-parties";

export function createListDisclosurePolicyRequest(overrides: Partial<ListDisclosurePoliciesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
