/**
 * CreateKnowledgeAnnotation DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { KnowledgeAnnotationCreateRequest } from "@phytoseal/core/classifications";
import { classificationsSchemas } from "@phytoseal/core/classifications";

export function createCreateKnowledgeAnnotationRequest(overrides: Partial<KnowledgeAnnotationCreateRequest> = {}) {
  const raw = {
    annotation: overrides.annotation ?? faker.lorem.word(),
    materialPattern: overrides.materialPattern ?? faker.lorem.word(),
    ...overrides,
  };

  return classificationsSchemas.KnowledgeAnnotationCreateRequest.parse(raw);
}
