/**
 * ExecuteGetCycleTimeReport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetCycleTimeReport Use Case
 *
 * DDD: Application use case for get Report.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetCycleTimeReportInput, GetCycleTimeReportOutput } from "../dto/report.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { ReportRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetCycleTimeReport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly report: ReportRepository
  ) {}

  async execute(input: GetCycleTimeReportInput): Promise<GetCycleTimeReportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mtrId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).reportId) {
      throw new ValidationError("reportId is required");
    }
    const reportId = (input as any).reportId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.report.getCycleTimeReport({ reportId: reportId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${reportId}`);
    }

    return entity as GetCycleTimeReportOutput;
  }
}
