/**
 * Routes for DisclosurePolicy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createDisclosurePolicy, getDisclosurePolicy, listDisclosurePolicies, replaceDisclosurePolicy } from "../handlers/disclosure-policy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { DisclosurePolicyCreateRequest, DisclosurePolicyReplaceRequest } from "@phytoseal/core/port-parties/types";

// Fastify types are available globally
export async function disclosurePolicyRoutes(fastify: FastifyInstance) {
  // POST /v1/disclosure-policies (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/disclosure-policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: DisclosurePolicyCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPortPartiesDependenciesForRequest();
        await createDisclosurePolicy(request, reply, deps);
      });
    }
  );


  // GET /v1/disclosure-policies (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/disclosure-policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPortPartiesDependenciesForRequest();
        await listDisclosurePolicies(request, reply, deps);
      });
    }
  );


  // GET /v1/disclosure-policies/{policyId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/disclosure-policies/:policyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPortPartiesDependenciesForRequest();
        await getDisclosurePolicy(request, reply, deps);
      });
    }
  );


  // PUT /v1/disclosure-policies/{policyId} (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/disclosure-policies/:policyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: DisclosurePolicyReplaceRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPortPartiesDependenciesForRequest();
        await replaceDisclosurePolicy(request, reply, deps);
      });
    }
  );


}
