/**
 * Routes for Invite
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { invitePortParty } from "../handlers/invite.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { PortPartyInviteRequest } from "@phytoseal/core/port-parties/types";

// Fastify types are available globally
export async function inviteRoutes(fastify: FastifyInstance) {
  // POST /v1/port-parties/{partyId}/invite (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/port-parties/:partyId/invite",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { partyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: PortPartyInviteRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPortPartiesDependenciesForRequest();
        await invitePortParty(request, reply, deps);
      });
    }
  );


}
