/**
 * Routes for PortParty
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createPortParty, getPortParty, listPortParties, updatePortParty } from "../handlers/port-party.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { PortPartyCreateRequest, PortPartyUpdateRequest } from "@phytoseal/core/port-parties/types";

// Fastify types are available globally
export async function portPartyRoutes(fastify: FastifyInstance) {
  // POST /v1/port-parties (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/port-parties",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: PortPartyCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPortPartiesDependenciesForRequest();
        await createPortParty(request, reply, deps);
      });
    }
  );


  // GET /v1/port-parties (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/port-parties",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPortPartiesDependenciesForRequest();
        await listPortParties(request, reply, deps);
      });
    }
  );


  // GET /v1/port-parties/{partyId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/port-parties/:partyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { partyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPortPartiesDependenciesForRequest();
        await getPortParty(request, reply, deps);
      });
    }
  );


  // PATCH /v1/port-parties/{partyId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/port-parties/:partyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { partyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: PortPartyUpdateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPortPartiesDependenciesForRequest();
        await updatePortParty(request, reply, deps);
      });
    }
  );


}
