/**
 * EvidencePack Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { EvidencePackEntity } from "@phytoseal/core/evidence-packs/models/index.js";
import { evidencePacksSchemas } from "@phytoseal/core/evidence-packs";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "evd";

export function createEvidencePack(overrides: Partial<EvidencePackEntity> = {}) {
  const raw = {
    id: overrides.id ?? `evd_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    certificateCount: overrides.certificateCount ?? faker.number.int({ min: 1, max: 100 }),
    classificationReviewCount: overrides.classificationReviewCount ?? faker.number.int({ min: 1, max: 100 }),
    packHash: overrides.packHash ?? faker.lorem.word(),
    period: overrides.period ?? faker.lorem.word(),
    status: overrides.status ?? "generating",
    ...overrides,
  };

  return evidencePacksSchemas.EvidencePack.parse(raw);
}

export function evidencePackBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createEvidencePack(overrides));
}
