/**
 * LegalHoldRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LegalHoldRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LegalHoldRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LegalHoldRepository,
} from "@phytoseal/services/legal-holds";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LegalHoldRepositoryDdb } from "./legal-hold-repository.ddb.js";

/**
 * LegalHoldRepositoryAdapter
 *
 * Implements LegalHoldRepository port for infrastructure layer.
 */
export class LegalHoldRepositoryAdapter implements LegalHoldRepository {
  private readonly ddb: LegalHoldRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LegalHoldRepositoryDdb(this.dynamoClient);
  }

  async listLegalHolds(input: Parameters<LegalHoldRepository['listLegalHolds']>[0]): Promise<Awaited<ReturnType<LegalHoldRepository['listLegalHolds']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listLegalHolds(input);
  }

  async createLegalHold(input: Parameters<LegalHoldRepository['createLegalHold']>[0]): Promise<Awaited<ReturnType<LegalHoldRepository['createLegalHold']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createLegalHold(input);
  }

  async getLegalHold(input: Parameters<LegalHoldRepository['getLegalHold']>[0]): Promise<Awaited<ReturnType<LegalHoldRepository['getLegalHold']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getLegalHold(input);
  }
}
