/**
 * ReleaseLegalHold handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { releaseLegalHold } from "@phytoseal/api-server/domains/legal-holds/handlers";
import type { LegalHoldsDDDDependencies } from "@phytoseal/api-server/domains/legal-holds";
import { createCreateReleaseRequest } from "@phytoseal/factories/legal-holds";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@phytoseal/tests/shared";
import { LEGALHOLDS_USE_CASES } from "../__factories__/use-cases.js";

describe("ReleaseLegalHold", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: LegalHoldsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<LegalHoldsDDDDependencies>(
      LEGALHOLDS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateReleaseRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeReleaseLegalHold, "execute").mockResolvedValue(useCaseResult);

    await releaseLegalHold(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeReleaseLegalHold.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
