/**
 * ClassificationProposal DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClassificationProposal DTOs
 *
 * DDD: Application DTOs for ClassificationProposal use cases.
 */

import type { ClassificationProposalCreateRequest, GetClassificationProposalParams, ListClassificationProposalsParams } from "@phytoseal/core/classifications/types";

export type ListClassificationProposalsInput = ListClassificationProposalsParams;

export type CreateClassificationProposalInput = ClassificationProposalCreateRequest;

export type GetClassificationProposalInput = GetClassificationProposalParams;

export type ListClassificationProposalsOutput = {};

export type CreateClassificationProposalOutput = {};

export type GetClassificationProposalOutput = {};
