/**
 * KnowledgeAnnotation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KnowledgeAnnotation DTOs
 *
 * DDD: Application DTOs for KnowledgeAnnotation use cases.
 */

import type { GetKnowledgeAnnotationParams, KnowledgeAnnotationCreateRequest, ListKnowledgeAnnotationsParams } from "@phytoseal/core/classifications/types";

export type ListKnowledgeAnnotationsInput = ListKnowledgeAnnotationsParams;

export type CreateKnowledgeAnnotationInput = KnowledgeAnnotationCreateRequest;

export type GetKnowledgeAnnotationInput = GetKnowledgeAnnotationParams;

export type ListKnowledgeAnnotationsOutput = {};

export type CreateKnowledgeAnnotationOutput = {};

export type GetKnowledgeAnnotationOutput = {};
