/**
 * CreateCertificate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CertificateCreateRequest } from "@phytoseal/core/certificates";
import { certificatesSchemas } from "@phytoseal/core/certificates";

export function createCreateCertificateRequest(overrides: Partial<CertificateCreateRequest> = {}) {
  const raw = {
    certificateType: overrides.certificateType ?? "phytosanitary",
    exportAuthorityId: overrides.exportAuthorityId ?? faker.string.uuid(),
    payloadHash: overrides.payloadHash ?? faker.lorem.word(),
    shipmentRef: overrides.shipmentRef ?? faker.lorem.word(),
    ...overrides,
  };

  return certificatesSchemas.CertificateCreateRequest.parse(raw);
}
