/**
 * ListCertificate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListCertificatesParams } from "@phytoseal/core/certificates";

export function createListCertificateRequest(overrides: Partial<ListCertificatesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
