/**
 * Amendments DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: amendments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Amendments Domain Module - Composition root
 *
 * DDD: Composition root for amendments domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AmendmentRepositoryAdapter,
  ApproveRepositoryAdapter,
  RejectRepositoryAdapter,
} from "@phytoseal/adapters/amendments";
import { getIdGeneratorService } from "@phytoseal/adapters";
import type { AdapterDynamoDBClient } from "@phytoseal/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApproveAmendment,
  ExecuteCreateCertificateAmendment,
  ExecuteGetAmendment,
  ExecuteListAmendments,
  ExecuteRejectAmendment,
} from "@phytoseal/services/amendments/usecases";
// Ports (interfaces)
import type {
  AmendmentRepository,
  ApproveRepository,
  RejectRepository,
} from "@phytoseal/services/amendments/ports";

export interface AmendmentsDomainModule {
  repos: {
    amendments: AmendmentRepository;
    approves: ApproveRepository;
    rejects: RejectRepository;
  };
  useCases: {
    amendments: {
      create: ExecuteCreateCertificateAmendment;
      get: ExecuteGetAmendment;
      list: ExecuteListAmendments;
    };
    approves: {
      create: ExecuteApproveAmendment;
    };
    rejects: {
      create: ExecuteRejectAmendment;
    };
  };
}

export function buildAmendmentsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AmendmentsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      amendments?: AmendmentRepository;
      approves?: ApproveRepository;
      rejects?: RejectRepository;
    } = {};

    obj.amendments = new AmendmentRepositoryAdapter(dynamoClient);
    obj.approves = new ApproveRepositoryAdapter(dynamoClient);
    obj.rejects = new RejectRepositoryAdapter(dynamoClient);
    return {
      amendments: obj.amendments!,
      approves: obj.approves!,
      rejects: obj.rejects!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    amendments: {
      create: new ExecuteCreateCertificateAmendment(executionContext, idGenerator, repos.amendments),
      get: new ExecuteGetAmendment(executionContext, idGenerator, repos.amendments),
      list: new ExecuteListAmendments(executionContext, idGenerator, repos.amendments),
    },
    approves: {
      create: new ExecuteApproveAmendment(executionContext, idGenerator, repos.approves),
    },
    rejects: {
      create: new ExecuteRejectAmendment(executionContext, idGenerator, repos.rejects),
    },
  };
  return { repos, useCases: useCases as AmendmentsDomainModule["useCases"] };
}
