/**
 * InviteRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * InviteRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements InviteRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  InviteRepository,
} from "@phytoseal/services/port-parties";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { InviteRepositoryDdb } from "./invite-repository.ddb.js";

/**
 * InviteRepositoryAdapter
 *
 * Implements InviteRepository port for infrastructure layer.
 */
export class InviteRepositoryAdapter implements InviteRepository {
  private readonly ddb: InviteRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new InviteRepositoryDdb(this.dynamoClient);
  }

  async invitePortParty(input: Parameters<InviteRepository['invitePortParty']>[0]): Promise<Awaited<ReturnType<InviteRepository['invitePortParty']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.invitePortParty(input);
  }
}
