/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @phytoseal/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@phytoseal/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@phytoseal/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@phytoseal/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@phytoseal/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@phytoseal/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _amendments from "./amendments/index.js";
import * as _certificates from "./certificates/index.js";
import * as _classifications from "./classifications/index.js";
import * as _evidencePacks from "./evidence-packs/index.js";
import * as _identity from "./identity/index.js";
import * as _legalHolds from "./legal-holds/index.js";
import * as _metrics from "./metrics/index.js";
import * as _portParties from "./port-parties/index.js";

// Export as namespaces
export const _shared = __shared;
export const amendments = _amendments;
export const certificates = _certificates;
export const classifications = _classifications;
export const evidencePacks = _evidencePacks;
export const identity = _identity;
export const legalHolds = _legalHolds;
export const metrics = _metrics;
export const portParties = _portParties;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@phytoseal/core"; activity.types.*
//   - Direct exports: import * from "@phytoseal/core/activity/types/index.js"
//   - Direct exports: import * from "@phytoseal/core/activity/repositories/index.js"
//   - Direct exports: import * from "@phytoseal/core/activity/models/index.js"
//   - Direct exports: import * from "@phytoseal/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Amendments Service
export { schemas as AmendmentsSchemas } from "./amendments/schemas/amendments.schemas.js";

// Certificates Service
export { schemas as CertificatesSchemas } from "./certificates/schemas/certificates.schemas.js";

// Classifications Service
export { schemas as ClassificationsSchemas } from "./classifications/schemas/classifications.schemas.js";

// EvidencePacks Service
export { schemas as EvidencePacksSchemas } from "./evidence-packs/schemas/evidence-packs.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// LegalHolds Service
export { schemas as LegalHoldsSchemas } from "./legal-holds/schemas/legal-holds.schemas.js";

// Metrics Service
export { schemas as MetricsSchemas } from "./metrics/schemas/metrics.schemas.js";

// PortParties Service
export { schemas as PortPartiesSchemas } from "./port-parties/schemas/port-parties.schemas.js";

