/**
 * Certificate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Certificate DTOs
 *
 * DDD: Application DTOs for Certificate use cases.
 */

import type { CertificateCreateRequest, GetCertificateParams, ListCertificatesParams } from "@phytoseal/core/certificates/types";

export type ListCertificatesInput = ListCertificatesParams;

export type CreateCertificateInput = CertificateCreateRequest;

export type GetCertificateInput = GetCertificateParams;

export type ListCertificatesOutput = {};

export type CreateCertificateOutput = {};

export type GetCertificateOutput = {};
