/**
 * Event DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Event DTOs
 *
 * DDD: Application DTOs for Event use cases.
 */

import type { ListCertificateEventsParams } from "@phytoseal/core/certificates/types";

export type ListCertificateEventsInput = ListCertificateEventsParams;

export type ListCertificateEventsOutput = {};
