/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * EvidencePacks Domain Use Cases
 * 
 * List of all use case names for the evidence-packs domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const EVIDENCEPACKS_USE_CASES = [
  "executeCreateEvidencePack",
  "executeGetEvidencePack",
  "executeListEvidencePacks"
] as const;
