/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-port-party.handler.test.js";
export * from "./get-port-party.handler.test.js";
export * from "./list-port-parties.handler.test.js";
export * from "./update-port-party.handler.test.js";
