/**
 * UpdatePortParty handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updatePortParty } from "@phytoseal/api-server/domains/port-parties/handlers";
import type { PortPartiesDDDDependencies } from "@phytoseal/api-server/domains/port-parties";
import { createPortParty as createPortPartyEntity } from "@phytoseal/factories/port-parties";
import { createUpdatePortPartyRequest } from "@phytoseal/factories/port-parties";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@phytoseal/tests/shared";
import { PORTPARTIES_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdatePortParty", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PortPartiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PortPartiesDDDDependencies>(
      PORTPARTIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createPortPartyEntity({ orgId });
    const input = createUpdatePortPartyRequest();
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { partyId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdatePortParty, "execute").mockResolvedValue(useCaseResult);

    await updatePortParty(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdatePortParty.execute).toHaveBeenCalledWith(expect.objectContaining({ partyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
