/**
 * CreateAmendment DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: amendments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AmendmentCreateRequest } from "@phytoseal/core/amendments";
import { amendmentsSchemas } from "@phytoseal/core/amendments";

export function createCreateAmendmentRequest(overrides: Partial<AmendmentCreateRequest> = {}) {
  const raw = {
    newPayloadHash: overrides.newPayloadHash ?? faker.lorem.word(),
    rationale: overrides.rationale ?? faker.lorem.word(),
    ...overrides,
  };

  return amendmentsSchemas.AmendmentCreateRequest.parse(raw);
}
