/**
 * ListAmendment DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: amendments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListAmendmentsParams } from "@phytoseal/core/amendments";

export function createListAmendmentRequest(overrides: Partial<ListAmendmentsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
