/**
 * Routes for Approve
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: amendments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { approveAmendment } from "../handlers/approve.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { AmendmentDecisionRequest } from "@phytoseal/core/amendments/types";

// Fastify types are available globally
export async function approveRoutes(fastify: FastifyInstance) {
  // POST /v1/amendments/{amendmentId}/approve (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/amendments/:amendmentId/approve",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { amendmentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: AmendmentDecisionRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAmendmentsDependenciesForRequest();
        await approveAmendment(request, reply, deps);
      });
    }
  );


}
