/**
 * Handlers for EvidencePack
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EvidencePacksDomainModule } from "../dependencies/evidence-packs-ddd.dependencies.js";
import type { EvidencePackCreateRequest } from "@phytoseal/core/evidence-packs/types";
import type { CreateEvidencePackInput, GetEvidencePackInput, ListEvidencePacksInput } from "@phytoseal/services/evidence-packs";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/evidence-packs
 * Operation: listEvidencePacks
 */
export async function listEvidencePacks(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], partyId?: string | string[], status?: string | string[], period?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: EvidencePacksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListEvidencePacksInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.evidencePacks.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/evidence-packs
 * Operation: createEvidencePack
 */
export async function createEvidencePack(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: EvidencePackCreateRequest }>,
  reply: FastifyReply,
  deps: EvidencePacksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateEvidencePackInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.evidencePacks.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/evidence-packs/{packId}
 * Operation: getEvidencePack
 */
export async function getEvidencePack(
  request: FastifyRequest<{ Params: { packId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EvidencePacksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetEvidencePackInput = {
    packId: request.params.packId,
  };
  const result = await deps.useCases.evidencePacks.get.execute(input);
  return reply.code(200).send(result);
}


