/**
 * GetLegalHold DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetLegalHoldParams } from "@phytoseal/core/legal-holds";

export function createGetLegalHoldRequest(overrides: Partial<GetLegalHoldParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
