/**
 * Handlers for DisclosurePolicy
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PortPartiesDomainModule } from "../dependencies/port-parties-ddd.dependencies.js";
import type { DisclosurePolicyCreateRequest, DisclosurePolicyReplaceRequest } from "@phytoseal/core/port-parties/types";
import type { CreateDisclosurePolicyInput, GetDisclosurePolicyInput, ListDisclosurePoliciesInput, ReplaceDisclosurePolicyInput } from "@phytoseal/services/port-parties";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/disclosure-policies
 * Operation: listDisclosurePolicies
 */
export async function listDisclosurePolicies(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], documentClass?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PortPartiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDisclosurePoliciesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.disclosurePolicies.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/disclosure-policies
 * Operation: createDisclosurePolicy
 */
export async function createDisclosurePolicy(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: DisclosurePolicyCreateRequest }>,
  reply: FastifyReply,
  deps: PortPartiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateDisclosurePolicyInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.disclosurePolicies.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/disclosure-policies/{policyId}
 * Operation: getDisclosurePolicy
 */
export async function getDisclosurePolicy(
  request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PortPartiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDisclosurePolicyInput = {
    policyId: request.params.policyId,
  };
  const result = await deps.useCases.disclosurePolicies.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/disclosure-policies/{policyId}
 * Operation: replaceDisclosurePolicy
 */
export async function replaceDisclosurePolicy(
  request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: DisclosurePolicyReplaceRequest }>,
  reply: FastifyReply,
  deps: PortPartiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ReplaceDisclosurePolicyInput = {
    policyId: request.params.policyId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.disclosurePolicies.get.execute(input);
  return reply.code(200).send(result);
}


