/**
 * Handlers for Invite
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PortPartiesDomainModule } from "../dependencies/port-parties-ddd.dependencies.js";
import type { PortPartyInviteRequest } from "@phytoseal/core/port-parties/types";
import type { InvitePortPartyInput } from "@phytoseal/services/port-parties";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/port-parties/{partyId}/invite
 * Operation: invitePortParty
 */
export async function invitePortParty(
  request: FastifyRequest<{ Params: { partyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: PortPartyInviteRequest }>,
  reply: FastifyReply,
  deps: PortPartiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: InvitePortPartyInput = {
    partyId: request.params.partyId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.invites.create.execute(input);
  return reply.code(200).send(result);
}


