/**
 * ListLegalHolds handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listLegalHolds } from "@phytoseal/api-server/domains/legal-holds/handlers";
import type { LegalHoldsDDDDependencies } from "@phytoseal/api-server/domains/legal-holds";
import { createLegalHold as createLegalHoldEntity } from "@phytoseal/factories/legal-holds";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@phytoseal/tests/shared";
import { LEGALHOLDS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListLegalHolds", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: LegalHoldsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<LegalHoldsDDDDependencies>(
      LEGALHOLDS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createLegalHoldEntity({ orgId }),
      createLegalHoldEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListLegalHolds, "execute").mockResolvedValue(useCaseResult);

    await listLegalHolds(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListLegalHolds.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
