/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAmendmentsDomainModule } from "./amendments/dependencies/amendments-ddd.dependencies.js";
export { buildCertificatesDomainModule } from "./certificates/dependencies/certificates-ddd.dependencies.js";
export { buildClassificationsDomainModule } from "./classifications/dependencies/classifications-ddd.dependencies.js";
export { buildEvidencePacksDomainModule } from "./evidence-packs/dependencies/evidence-packs-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildLegalHoldsDomainModule } from "./legal-holds/dependencies/legal-holds-ddd.dependencies.js";
export { buildMetricsDomainModule } from "./metrics/dependencies/metrics-ddd.dependencies.js";
export { buildPortPartiesDomainModule } from "./port-parties/dependencies/port-parties-ddd.dependencies.js";

// Export all domain dependency types
export type { AmendmentsDomainModule } from "./amendments/dependencies/amendments-ddd.dependencies.js";
export type { CertificatesDomainModule } from "./certificates/dependencies/certificates-ddd.dependencies.js";
export type { ClassificationsDomainModule } from "./classifications/dependencies/classifications-ddd.dependencies.js";
export type { EvidencePacksDomainModule } from "./evidence-packs/dependencies/evidence-packs-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { LegalHoldsDomainModule } from "./legal-holds/dependencies/legal-holds-ddd.dependencies.js";
export type { MetricsDomainModule } from "./metrics/dependencies/metrics-ddd.dependencies.js";
export type { PortPartiesDomainModule } from "./port-parties/dependencies/port-parties-ddd.dependencies.js";
