/**
 * Certificate Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/certificates.openapi.types.js";
import { schemas } from "../schemas/certificates.schemas.js";

/**
 * Entity: CertificateEntity
 * Description: Represents the Certificate domain model.
 * Source: schemas.Certificate
 * Type: Domain Entity (API)
 */
export const CertificateEntitySchema = schemas.Certificate;
export type CertificateEntity = components["schemas"]["Certificate"];
