/**
 * Routes for LegalHold
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createLegalHold, getLegalHold, listLegalHolds } from "../handlers/legal-hold.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { LegalHoldCreateRequest } from "@phytoseal/core/legal-holds/types";

// Fastify types are available globally
export async function legalHoldRoutes(fastify: FastifyInstance) {
  // POST /v1/legal-holds (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/legal-holds",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: LegalHoldCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLegalHoldsDependenciesForRequest();
        await createLegalHold(request, reply, deps);
      });
    }
  );


  // GET /v1/legal-holds (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/legal-holds",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLegalHoldsDependenciesForRequest();
        await listLegalHolds(request, reply, deps);
      });
    }
  );


  // GET /v1/legal-holds/{holdId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/legal-holds/:holdId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { holdId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLegalHoldsDependenciesForRequest();
        await getLegalHold(request, reply, deps);
      });
    }
  );


}
