/**
 * Routes for Release
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { releaseLegalHold } from "../handlers/release.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { LegalHoldReleaseRequest } from "@phytoseal/core/legal-holds/types";

// Fastify types are available globally
export async function releaseRoutes(fastify: FastifyInstance) {
  // POST /v1/legal-holds/{holdId}/release (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/legal-holds/:holdId/release",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { holdId: string }; Querystring: Record<string, string | string[] | undefined>; Body: LegalHoldReleaseRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLegalHoldsDependenciesForRequest();
        await releaseLegalHold(request, reply, deps);
      });
    }
  );


}
