/**
 * GetCycleTimeReport handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getCycleTimeReport } from "@phytoseal/api-server/domains/metrics/handlers";
import type { MetricsDDDDependencies } from "@phytoseal/api-server/domains/metrics";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@phytoseal/tests/shared";
import { METRICS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetCycleTimeReport", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: MetricsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<MetricsDDDDependencies>(
      METRICS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetCycleTimeReport, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { reportId: entity.id };

    await getCycleTimeReport(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetCycleTimeReport.execute).toHaveBeenCalledWith(expect.objectContaining({ reportId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { reportId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetCycleTimeReport, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getCycleTimeReport(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
