/**
 * Handlers for LegalHold
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { LegalHoldsDomainModule } from "../dependencies/legal-holds-ddd.dependencies.js";
import type { LegalHoldCreateRequest } from "@phytoseal/core/legal-holds/types";
import type { CreateLegalHoldInput, GetLegalHoldInput, ListLegalHoldsInput } from "@phytoseal/services/legal-holds";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/legal-holds
 * Operation: listLegalHolds
 */
export async function listLegalHolds(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], jurisdiction?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: LegalHoldsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListLegalHoldsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.legalHolds.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/legal-holds
 * Operation: createLegalHold
 */
export async function createLegalHold(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: LegalHoldCreateRequest }>,
  reply: FastifyReply,
  deps: LegalHoldsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateLegalHoldInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.legalHolds.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/legal-holds/{holdId}
 * Operation: getLegalHold
 */
export async function getLegalHold(
  request: FastifyRequest<{ Params: { holdId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: LegalHoldsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetLegalHoldInput = {
    holdId: request.params.holdId,
  };
  const result = await deps.useCases.legalHolds.get.execute(input);
  return reply.code(200).send(result);
}


