/**
 * Handlers for Release
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { LegalHoldsDomainModule } from "../dependencies/legal-holds-ddd.dependencies.js";
import type { LegalHoldReleaseRequest } from "@phytoseal/core/legal-holds/types";
import type { ReleaseLegalHoldInput } from "@phytoseal/services/legal-holds";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/legal-holds/{holdId}/release
 * Operation: releaseLegalHold
 */
export async function releaseLegalHold(
  request: FastifyRequest<{ Params: { holdId: string }; Querystring: Record<string, string | string[] | undefined>; Body: LegalHoldReleaseRequest }>,
  reply: FastifyReply,
  deps: LegalHoldsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ReleaseLegalHoldInput = {
    holdId: request.params.holdId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.releases.get.execute(input);
  return reply.code(200).send(result);
}


