/**
 * LegalHold Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/legal-holds.openapi.types.js";
import { schemas } from "../schemas/legal-holds.schemas.js";

/**
 * Entity: LegalHoldEntity
 * Description: Represents the LegalHold domain model.
 * Source: schemas.LegalHold
 * Type: Domain Entity (API)
 */
export const LegalHoldEntitySchema = schemas.LegalHold;
export type LegalHoldEntity = components["schemas"]["LegalHold"];
