/**
 * CreatePortParty DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PortPartyCreateRequest } from "@phytoseal/core/port-parties";
import { portPartiesSchemas } from "@phytoseal/core/port-parties";

export function createCreatePortPartyRequest(overrides: Partial<PortPartyCreateRequest> = {}) {
  const raw = {
    name: overrides.name ?? faker.person.fullName(),
    partyType: overrides.partyType ?? "shipper",
    ...overrides,
  };

  return portPartiesSchemas.PortPartyCreateRequest.parse(raw);
}
