/**
 * CreateReport DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CycleTimeReportCreateRequest } from "@phytoseal/core/metrics";
import { metricsSchemas } from "@phytoseal/core/metrics";

export function createCreateReportRequest(overrides: Partial<CycleTimeReportCreateRequest> = {}) {
  const raw = {
    period: overrides.period ?? faker.lorem.word(),
    ...overrides,
  };

  return metricsSchemas.CycleTimeReportCreateRequest.parse(raw);
}
