/**
 * ListReport DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListCycleTimeReportsParams } from "@phytoseal/core/metrics";

export function createListReportRequest(overrides: Partial<ListCycleTimeReportsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
