/**
 * Classifications Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createClassificationProposal_Body = z
  .object({
    materialDescription: z.string().min(1).max(4000),
    materialNumber: z.string().optional(),
    proposedHsCode: z.string().optional(),
    proposedEccn: z.string().optional(),
    confidence: z.number().gte(0).lte(1).optional(),
    rationale: z.string().max(8000).optional(),
  })
  .passthrough();
const reviewClassificationProposal_Body = z
  .object({
    outcome: z.enum(['approved', 'overridden', 'rejected', 'deferred']),
    finalHsCode: z.string().optional(),
    brokerAnnotation: z.string().max(4000).optional(),
  })
  .passthrough();
const createKnowledgeAnnotation_Body = z
  .object({
    materialPattern: z.string().min(1).max(500),
    annotation: z.string().min(1).max(4000),
    linkedProposalId: z
      .string()
      .regex(/^cls_[0-9A-HJKMNP-TV-Z]{26}$/)
      .optional(),
    promotedToPlaybook: z.boolean().optional().default(false),
  })
  .passthrough();

export const schemas: any = {
  createClassificationProposal_Body,
  reviewClassificationProposal_Body,
  createKnowledgeAnnotation_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/classification-proposals',
    alias: 'listClassificationProposals',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().min(1).max(512).optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z
          .enum(['proposed', 'approved', 'overridden', 'rejected', 'deferred'])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^cls_[0-9A-HJKMNP-TV-Z]{26}$/),
                  materialDescription: z.string().min(1).max(4000),
                  materialNumber: z.string().optional(),
                  proposedHsCode: z.string().optional(),
                  proposedEccn: z.string().optional(),
                  confidence: z.number().gte(0).lte(1).optional(),
                  rationale: z.string().max(8000).optional(),
                  status: z.enum([
                    'proposed',
                    'approved',
                    'overridden',
                    'rejected',
                    'deferred',
                  ]),
                  finalHsCode: z.string().optional(),
                  brokerAnnotation: z.string().max(4000).optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/classification-proposals',
    alias: 'createClassificationProposal',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createClassificationProposal_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^cls_[0-9A-HJKMNP-TV-Z]{26}$/),
            materialDescription: z.string().min(1).max(4000),
            materialNumber: z.string().optional(),
            proposedHsCode: z.string().optional(),
            proposedEccn: z.string().optional(),
            confidence: z.number().gte(0).lte(1).optional(),
            rationale: z.string().max(8000).optional(),
            status: z.enum([
              'proposed',
              'approved',
              'overridden',
              'rejected',
              'deferred',
            ]),
            finalHsCode: z.string().optional(),
            brokerAnnotation: z.string().max(4000).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/classification-proposals/:proposalId',
    alias: 'getClassificationProposal',
    requestFormat: 'json',
    parameters: [
      {
        name: 'proposalId',
        type: 'Path',
        schema: z.string().regex(/^cls_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^cls_[0-9A-HJKMNP-TV-Z]{26}$/),
            materialDescription: z.string().min(1).max(4000),
            materialNumber: z.string().optional(),
            proposedHsCode: z.string().optional(),
            proposedEccn: z.string().optional(),
            confidence: z.number().gte(0).lte(1).optional(),
            rationale: z.string().max(8000).optional(),
            status: z.enum([
              'proposed',
              'approved',
              'overridden',
              'rejected',
              'deferred',
            ]),
            finalHsCode: z.string().optional(),
            brokerAnnotation: z.string().max(4000).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/classification-proposals/:proposalId/review',
    alias: 'reviewClassificationProposal',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: reviewClassificationProposal_Body,
      },
      {
        name: 'proposalId',
        type: 'Path',
        schema: z.string().regex(/^cls_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^cls_[0-9A-HJKMNP-TV-Z]{26}$/),
            materialDescription: z.string().min(1).max(4000),
            materialNumber: z.string().optional(),
            proposedHsCode: z.string().optional(),
            proposedEccn: z.string().optional(),
            confidence: z.number().gte(0).lte(1).optional(),
            rationale: z.string().max(8000).optional(),
            status: z.enum([
              'proposed',
              'approved',
              'overridden',
              'rejected',
              'deferred',
            ]),
            finalHsCode: z.string().optional(),
            brokerAnnotation: z.string().max(4000).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/knowledge-annotations',
    alias: 'listKnowledgeAnnotations',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().min(1).max(512).optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
      {
        name: 'promotedToPlaybook',
        type: 'Query',
        schema: z.boolean().optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^kna_[0-9A-HJKMNP-TV-Z]{26}$/),
                  materialPattern: z.string().min(1).max(500),
                  annotation: z.string().min(1).max(4000),
                  linkedProposalId: z
                    .string()
                    .regex(/^cls_[0-9A-HJKMNP-TV-Z]{26}$/)
                    .optional(),
                  promotedToPlaybook: z.boolean(),
                  createdAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/knowledge-annotations',
    alias: 'createKnowledgeAnnotation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createKnowledgeAnnotation_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^kna_[0-9A-HJKMNP-TV-Z]{26}$/),
            materialPattern: z.string().min(1).max(500),
            annotation: z.string().min(1).max(4000),
            linkedProposalId: z
              .string()
              .regex(/^cls_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            promotedToPlaybook: z.boolean(),
            createdAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/knowledge-annotations/:annotationId',
    alias: 'getKnowledgeAnnotation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'annotationId',
        type: 'Path',
        schema: z.string().regex(/^kna_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^kna_[0-9A-HJKMNP-TV-Z]{26}$/),
            materialPattern: z.string().min(1).max(500),
            annotation: z.string().min(1).max(4000),
            linkedProposalId: z
              .string()
              .regex(/^cls_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            promotedToPlaybook: z.boolean(),
            createdAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios('https://api.phytoseal.local', endpoints);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
