/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@phytoseal/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@phytoseal/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@phytoseal/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _amendments from "./amendments/index.js";
import * as _certificates from "./certificates/index.js";
import * as _classifications from "./classifications/index.js";
import * as _evidencePacks from "./evidence-packs/index.js";
import * as _identity from "./identity/index.js";
import * as _legalHolds from "./legal-holds/index.js";
import * as _metrics from "./metrics/index.js";
import * as _portParties from "./port-parties/index.js";

// Export as namespaces
export const amendments = _amendments;
export const certificates = _certificates;
export const classifications = _classifications;
export const evidencePacks = _evidencePacks;
export const identity = _identity;
export const legalHolds = _legalHolds;
export const metrics = _metrics;
export const portParties = _portParties;
