/**
 * ExecuteListAmendments - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: amendments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAmendments Use Case
 *
 * DDD: Application use case for list Amendment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAmendmentsInput, ListAmendmentsOutput } from "../dto/amendment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { AmendmentRepository } from "../ports";

export class ExecuteListAmendments {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly amendment: AmendmentRepository
  ) {}

  async execute(input: ListAmendmentsInput): Promise<ListAmendmentsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.amdId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.amendment.listAmendments({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAmendmentsOutput;
  }
}
