/**
 * ExecuteRejectAmendment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: amendments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRejectAmendment Use Case
 *
 * DDD: Application use case for create Reject.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RejectAmendmentInput, RejectAmendmentOutput } from "../dto/reject.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { RejectRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRejectAmendment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly reject: RejectRepository
  ) {}

  async execute(input: RejectAmendmentInput): Promise<RejectAmendmentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.amdId();

    // All field names extracted from OpenAPI spec: note
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    // No required field validations    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (amendments domain)
    const entityId = this.idGenerator.amdId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.reject.rejectAmendment({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RejectAmendmentOutput;
  }
}
