/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./classification-proposal-repository.ddb.js";
export * from "./knowledge-annotation-repository.ddb.js";
export * from "./review-repository.ddb.js";
export * from "./classification-proposal-repository.adapter.js";
export * from "./knowledge-annotation-repository.adapter.js";
export * from "./review-repository.adapter.js";
