/**
 * KnowledgeAnnotationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KnowledgeAnnotationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements KnowledgeAnnotationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  KnowledgeAnnotationRepository,
} from "@phytoseal/services/classifications";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { KnowledgeAnnotationRepositoryDdb } from "./knowledge-annotation-repository.ddb.js";

/**
 * KnowledgeAnnotationRepositoryAdapter
 *
 * Implements KnowledgeAnnotationRepository port for infrastructure layer.
 */
export class KnowledgeAnnotationRepositoryAdapter implements KnowledgeAnnotationRepository {
  private readonly ddb: KnowledgeAnnotationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new KnowledgeAnnotationRepositoryDdb(this.dynamoClient);
  }

  async listKnowledgeAnnotations(input: Parameters<KnowledgeAnnotationRepository['listKnowledgeAnnotations']>[0]): Promise<Awaited<ReturnType<KnowledgeAnnotationRepository['listKnowledgeAnnotations']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listKnowledgeAnnotations(input);
  }

  async createKnowledgeAnnotation(input: Parameters<KnowledgeAnnotationRepository['createKnowledgeAnnotation']>[0]): Promise<Awaited<ReturnType<KnowledgeAnnotationRepository['createKnowledgeAnnotation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createKnowledgeAnnotation(input);
  }

  async getKnowledgeAnnotation(input: Parameters<KnowledgeAnnotationRepository['getKnowledgeAnnotation']>[0]): Promise<Awaited<ReturnType<KnowledgeAnnotationRepository['getKnowledgeAnnotation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getKnowledgeAnnotation(input);
  }
}
