/**
 * CreateClassificationProposal DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ClassificationProposalCreateRequest } from "@phytoseal/core/classifications";
import { classificationsSchemas } from "@phytoseal/core/classifications";

export function createCreateClassificationProposalRequest(overrides: Partial<ClassificationProposalCreateRequest> = {}) {
  const raw = {
    materialDescription: overrides.materialDescription ?? faker.lorem.sentence(),
    ...overrides,
  };

  return classificationsSchemas.ClassificationProposalCreateRequest.parse(raw);
}
