/**
 * GetClassificationProposal DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetClassificationProposalParams } from "@phytoseal/core/classifications";

export function createGetClassificationProposalRequest(overrides: Partial<GetClassificationProposalParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
