/**
 * CreateApprove DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: amendments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { AmendmentDecisionRequest } from "@phytoseal/core/amendments";
import { amendmentsSchemas } from "@phytoseal/core/amendments";

export function createCreateApproveRequest(overrides: Partial<AmendmentDecisionRequest> = {}) {
  const raw = {
    ...overrides,
  };

  return amendmentsSchemas.AmendmentDecisionRequest.parse(raw);
}
