/**
 * Handlers for CycleTime
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { MetricsDomainModule } from "../dependencies/metrics-ddd.dependencies.js";
import type { GetCycleTimeMetricsInput } from "@phytoseal/services/metrics";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/metrics/cycle-time
 * Operation: getCycleTimeMetrics
 */
export async function getCycleTimeMetrics(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { period?: string | string[], commodity?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: MetricsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCycleTimeMetricsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.cycleTimes.get.execute(input);
  return reply.code(200).send(result);
}


