/**
 * Handlers for Report
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { MetricsDomainModule } from "../dependencies/metrics-ddd.dependencies.js";
import type { CycleTimeReportCreateRequest } from "@phytoseal/core/metrics/types";
import type { CreateCycleTimeReportInput, GetCycleTimeReportInput, ListCycleTimeReportsInput } from "@phytoseal/services/metrics";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/metrics/reports
 * Operation: listCycleTimeReports
 */
export async function listCycleTimeReports(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], period?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: MetricsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListCycleTimeReportsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.reports.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/metrics/reports
 * Operation: createCycleTimeReport
 */
export async function createCycleTimeReport(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: CycleTimeReportCreateRequest }>,
  reply: FastifyReply,
  deps: MetricsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateCycleTimeReportInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.reports.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/metrics/reports/{reportId}
 * Operation: getCycleTimeReport
 */
export async function getCycleTimeReport(
  request: FastifyRequest<{ Params: { reportId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: MetricsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCycleTimeReportInput = {
    reportId: request.params.reportId,
  };
  const result = await deps.useCases.reports.get.execute(input);
  return reply.code(200).send(result);
}


