/**
 * GetEvidencePack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence-packs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getEvidencePack } from "@phytoseal/api-server/domains/evidence-packs/handlers";
import type { EvidencePacksDDDDependencies } from "@phytoseal/api-server/domains/evidence-packs";
import { createEvidencePack as createEvidencePackEntity } from "@phytoseal/factories/evidence-packs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@phytoseal/tests/shared";
import { EVIDENCEPACKS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetEvidencePack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EvidencePacksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EvidencePacksDDDDependencies>(
      EVIDENCEPACKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createEvidencePackEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetEvidencePack, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { packId: entity.id };

    await getEvidencePack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetEvidencePack.execute).toHaveBeenCalledWith(expect.objectContaining({ packId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { packId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetEvidencePack, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getEvidencePack(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
