/**
 * Metrics DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Metrics Domain Module - Composition root
 *
 * DDD: Composition root for metrics domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CycleTimeRepositoryAdapter,
  ReportRepositoryAdapter,
} from "@phytoseal/adapters/metrics";
import { getIdGeneratorService } from "@phytoseal/adapters";
import type { AdapterDynamoDBClient } from "@phytoseal/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateCycleTimeReport,
  ExecuteGetCycleTimeReport,
  ExecuteListCycleTimeReports,
} from "@phytoseal/services/metrics/usecases";
// Ports (interfaces)
import type {
  CycleTimeRepository,
  ReportRepository,
} from "@phytoseal/services/metrics/ports";

export interface MetricsDomainModule {
  repos: {
    cycleTimes: CycleTimeRepository;
    reports: ReportRepository;
  };
  useCases: {
    reports: {
      create: ExecuteCreateCycleTimeReport;
      get: ExecuteGetCycleTimeReport;
      list: ExecuteListCycleTimeReports;
    };
  };
}

export function buildMetricsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): MetricsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      cycleTimes?: CycleTimeRepository;
      reports?: ReportRepository;
    } = {};

    obj.cycleTimes = new CycleTimeRepositoryAdapter(dynamoClient);
    obj.reports = new ReportRepositoryAdapter(dynamoClient);
    return {
      cycleTimes: obj.cycleTimes!,
      reports: obj.reports!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    reports: {
      create: new ExecuteCreateCycleTimeReport(executionContext, idGenerator, repos.reports),
      get: new ExecuteGetCycleTimeReport(executionContext, idGenerator, repos.reports),
      list: new ExecuteListCycleTimeReports(executionContext, idGenerator, repos.reports),
    },
  };
  return { repos, useCases: useCases as MetricsDomainModule["useCases"] };
}
