/**
 * AmendmentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: amendments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AmendmentRepository Port
 *
 * DDD: Application port for amendmentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateCertificateAmendmentInput, CreateCertificateAmendmentOutput, GetAmendmentInput, GetAmendmentOutput, ListAmendmentsInput, ListAmendmentsOutput } from "../dto/amendment.dto";
export interface AmendmentRepository {
  listAmendments(input: ListAmendmentsInput): Promise<ListAmendmentsOutput>;
  createCertificateAmendment(input: CreateCertificateAmendmentInput): Promise<CreateCertificateAmendmentOutput>;
  getAmendment(input: GetAmendmentInput): Promise<GetAmendmentOutput>;
}

export type { CreateCertificateAmendmentInput, CreateCertificateAmendmentOutput, GetAmendmentInput, GetAmendmentOutput, ListAmendmentsInput, ListAmendmentsOutput } from "../dto/amendment.dto";
