/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: legal-holds
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the legal-holds domain.
 * Use these factories in tests to create test data.
 */

export { createCreateLegalHoldRequest } from "./legal-hold/dto/create-legal-hold.dto.factory.js";
export { createCreateReleaseRequest } from "./release/dto/create-release.dto.factory.js";
export { createLegalHold } from "./legal-hold/entity/legal-hold.entity.factory.js";
