/**
 * CertificateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CertificateRepository Port
 *
 * DDD: Application port for certificaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateCertificateInput, CreateCertificateOutput, GetCertificateInput, GetCertificateOutput, ListCertificatesInput, ListCertificatesOutput } from "../dto/certificate.dto";
export interface CertificateRepository {
  listCertificates(input: ListCertificatesInput): Promise<ListCertificatesOutput>;
  createCertificate(input: CreateCertificateInput): Promise<CreateCertificateOutput>;
  getCertificate(input: GetCertificateInput): Promise<GetCertificateOutput>;
}

export type { CreateCertificateInput, CreateCertificateOutput, GetCertificateInput, GetCertificateOutput, ListCertificatesInput, ListCertificatesOutput } from "../dto/certificate.dto";
