/**
 * Handlers for Certificate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CertificatesDomainModule } from "../dependencies/certificates-ddd.dependencies.js";
import type { CertificateCreateRequest } from "@phytoseal/core/certificates/types";
import type { CreateCertificateInput, GetCertificateInput, ListCertificatesInput } from "@phytoseal/services/certificates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/certificates
 * Operation: listCertificates
 */
export async function listCertificates(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], certificateType?: string | string[], shipmentRef?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CertificatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListCertificatesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.certificates.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/certificates
 * Operation: createCertificate
 */
export async function createCertificate(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: CertificateCreateRequest }>,
  reply: FastifyReply,
  deps: CertificatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateCertificateInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.certificates.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/certificates/{certificateId}
 * Operation: getCertificate
 */
export async function getCertificate(
  request: FastifyRequest<{ Params: { certificateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CertificatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCertificateInput = {
    certificateId: request.params.certificateId,
  };
  const result = await deps.useCases.certificates.get.execute(input);
  return reply.code(200).send(result);
}


