/**
 * Handlers for Decision
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CertificatesDomainModule } from "../dependencies/certificates-ddd.dependencies.js";
import type { CertificateDecisionRequest } from "@phytoseal/core/certificates/types";
import type { DecideCertificateInput } from "@phytoseal/services/certificates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/certificates/{certificateId}/decision
 * Operation: decideCertificate
 */
export async function decideCertificate(
  request: FastifyRequest<{ Params: { certificateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: CertificateDecisionRequest }>,
  reply: FastifyReply,
  deps: CertificatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: DecideCertificateInput = {
    certificateId: request.params.certificateId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.decisions.get.execute(input);
  return reply.code(200).send(result);
}


