/**
 * Handlers for Event
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CertificatesDomainModule } from "../dependencies/certificates-ddd.dependencies.js";
import type { ListCertificateEventsInput } from "@phytoseal/services/certificates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/certificates/{certificateId}/events
 * Operation: listCertificateEvents
 */
export async function listCertificateEvents(
  request: FastifyRequest<{ Params: { certificateId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CertificatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListCertificateEventsInput = {
    certificateId: request.params.certificateId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.events.list.execute(input);
  return reply.code(200).send(result);
}


