/**
 * Invite DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Invite DTOs
 *
 * DDD: Application DTOs for Invite use cases.
 */

import type { InvitePortPartyParams, PortPartyInviteRequest } from "@phytoseal/core/port-parties/types";

export type InvitePortPartyInput = InvitePortPartyParams & PortPartyInviteRequest;

export type InvitePortPartyOutput = {};
