/**
 * PortParty DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PortParty DTOs
 *
 * DDD: Application DTOs for PortParty use cases.
 */

import type { GetPortPartyParams, ListPortPartiesParams, PortPartyCreateRequest, PortPartyUpdateRequest, UpdatePortPartyParams } from "@phytoseal/core/port-parties/types";

export type ListPortPartiesInput = ListPortPartiesParams;

export type CreatePortPartyInput = PortPartyCreateRequest;

export type GetPortPartyInput = GetPortPartyParams;

export type UpdatePortPartyInput = UpdatePortPartyParams & PortPartyUpdateRequest;

export type ListPortPartiesOutput = {};

export type CreatePortPartyOutput = {};

export type GetPortPartyOutput = {};

export type UpdatePortPartyOutput = {};
