/**
 * Simulate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Simulate DTOs
 *
 * DDD: Application DTOs for Simulate use cases.
 */

import type { DisclosurePolicySimulateRequest, SimulateDisclosurePolicyParams } from "@phytoseal/core/port-parties/types";

export type SimulateDisclosurePolicyInput = SimulateDisclosurePolicyParams & DisclosurePolicySimulateRequest;

export type SimulateDisclosurePolicyOutput = {};
