/**
 * CreateSimulate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { DisclosurePolicySimulateRequest } from "@phytoseal/core/port-parties";
import { portPartiesSchemas } from "@phytoseal/core/port-parties";

export function createCreateSimulateRequest(overrides: Partial<DisclosurePolicySimulateRequest> = {}) {
  const raw = {
    partyRole: overrides.partyRole ?? "shipper",
    ...overrides,
  };

  return portPartiesSchemas.DisclosurePolicySimulateRequest.parse(raw);
}
