/**
 * Repository interface for ClassificationProposal
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ClassificationProposalEntity
} from "../models/classification-proposal.entity.js";
import type {
  ListClassificationProposalsParams,
  ClassificationProposalCreateRequest
} from "../types/index.js";
/**
 * ClassificationProposalRepository Interface
 */
export interface ClassificationProposalRepository extends CreateReadRepository<ClassificationProposalEntity, ClassificationProposalCreateRequest, string, ListClassificationProposalsParams> {

}
