/**
 * Repository interface for KnowledgeAnnotation
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  KnowledgeAnnotationEntity
} from "../models/knowledge-annotation.entity.js";
import type {
  ListKnowledgeAnnotationsParams,
  KnowledgeAnnotationCreateRequest
} from "../types/index.js";
/**
 * KnowledgeAnnotationRepository Interface
 */
export interface KnowledgeAnnotationRepository extends CreateReadRepository<KnowledgeAnnotationEntity, KnowledgeAnnotationCreateRequest, string, ListKnowledgeAnnotationsParams> {

}
