/**
 * ExecuteListPortParties - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPortParties Use Case
 *
 * DDD: Application use case for list PortParty.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPortPartiesInput, ListPortPartiesOutput } from "../dto/port-party.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { PortPartyRepository } from "../ports";

export class ExecuteListPortParties {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly portParty: PortPartyRepository
  ) {}

  async execute(input: ListPortPartiesInput): Promise<ListPortPartiesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ptyId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.portParty.listPortParties({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPortPartiesOutput;
  }
}
