/**
 * ExecuteCreatePortParty - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreatePortParty Use Case
 *
 * DDD: Application use case for create PortParty.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreatePortPartyInput, CreatePortPartyOutput } from "../dto/port-party.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { PortPartyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreatePortParty {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly portParty: PortPartyRepository
  ) {}

  async execute(input: CreatePortPartyInput): Promise<CreatePortPartyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ptyId();

    // All field names extracted from OpenAPI spec: disclosureProfile, documentClassesEnabled, name, partyType
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.partyType) {
      throw new ValidationError("partyType is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (port-parties domain)
    const entityId = this.idGenerator.ptyId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.portParty.createPortParty({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreatePortPartyOutput;
  }
}
