/**
 * ExecuteCreateDisclosurePolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateDisclosurePolicy Use Case
 *
 * DDD: Application use case for create DisclosurePolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateDisclosurePolicyInput, CreateDisclosurePolicyOutput } from "../dto/disclosure-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { DisclosurePolicyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateDisclosurePolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly disclosurePolicy: DisclosurePolicyRepository
  ) {}

  async execute(input: CreateDisclosurePolicyInput): Promise<CreateDisclosurePolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ptyId();

    // All field names extracted from OpenAPI spec: documentClass, name, rules, status
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.rules) {
      throw new ValidationError("rules is required");
    }
    if (!input.documentClass) {
      throw new ValidationError("documentClass is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (port-parties domain)
    const entityId = this.idGenerator.ptyId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.disclosurePolicy.createDisclosurePolicy({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateDisclosurePolicyOutput;
  }
}
