/**
 * ExecuteReplaceDisclosurePolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteReplaceDisclosurePolicy Use Case
 *
 * DDD: Application use case for get DisclosurePolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ReplaceDisclosurePolicyInput, ReplaceDisclosurePolicyOutput } from "../dto/disclosure-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { DisclosurePolicyRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteReplaceDisclosurePolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly disclosurePolicy: DisclosurePolicyRepository
  ) {}

  async execute(input: ReplaceDisclosurePolicyInput): Promise<ReplaceDisclosurePolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ptyId();

    // All field names extracted from OpenAPI spec: documentClass, name, rules, status
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).policyId) {
      throw new ValidationError("policyId is required");
    }
    const policyId = (input as any).policyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.disclosurePolicy.replaceDisclosurePolicy({ policyId: policyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${policyId}`);
    }

    return entity as ReplaceDisclosurePolicyOutput;
  }
}
