/**
 * ExecuteGetPortParty - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: port-parties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetPortParty Use Case
 *
 * DDD: Application use case for get PortParty.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetPortPartyInput, GetPortPartyOutput } from "../dto/port-party.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { PortPartyRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetPortParty {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly portParty: PortPartyRepository
  ) {}

  async execute(input: GetPortPartyInput): Promise<GetPortPartyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ptyId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).partyId) {
      throw new ValidationError("partyId is required");
    }
    const partyId = (input as any).partyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.portParty.getPortParty({ partyId: partyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${partyId}`);
    }

    return entity as GetPortPartyOutput;
  }
}
