/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./certificate-repository.ddb.js";
export * from "./decision-repository.ddb.js";
export * from "./event-repository.ddb.js";
export * from "./present-repository.ddb.js";
export * from "./certificate-repository.adapter.js";
export * from "./decision-repository.adapter.js";
export * from "./event-repository.adapter.js";
export * from "./present-repository.adapter.js";
