/**
 * PresentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PresentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PresentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PresentRepository,
} from "@phytoseal/services/certificates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PresentRepositoryDdb } from "./present-repository.ddb.js";

/**
 * PresentRepositoryAdapter
 *
 * Implements PresentRepository port for infrastructure layer.
 */
export class PresentRepositoryAdapter implements PresentRepository {
  private readonly ddb: PresentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PresentRepositoryDdb(this.dynamoClient);
  }

  async presentCertificate(input: Parameters<PresentRepository['presentCertificate']>[0]): Promise<Awaited<ReturnType<PresentRepository['presentCertificate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.presentCertificate(input);
  }
}
