/**
 * ExecuteReviewClassificationProposal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteReviewClassificationProposal Use Case
 *
 * DDD: Application use case for get Review.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ReviewClassificationProposalInput, ReviewClassificationProposalOutput } from "../dto/review.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { ReviewRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteReviewClassificationProposal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly review: ReviewRepository
  ) {}

  async execute(input: ReviewClassificationProposalInput): Promise<ReviewClassificationProposalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.clsId();

    // All field names extracted from OpenAPI spec: brokerAnnotation, finalHsCode, outcome
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).proposalId) {
      throw new ValidationError("proposalId is required");
    }
    const proposalId = (input as any).proposalId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.review.reviewClassificationProposal({ proposalId: proposalId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${proposalId}`);
    }

    return entity as ReviewClassificationProposalOutput;
  }
}
