/**
 * ExecuteCreateKnowledgeAnnotation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateKnowledgeAnnotation Use Case
 *
 * DDD: Application use case for create KnowledgeAnnotation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateKnowledgeAnnotationInput, CreateKnowledgeAnnotationOutput } from "../dto/knowledge-annotation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { KnowledgeAnnotationRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateKnowledgeAnnotation {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly knowledgeAnnotation: KnowledgeAnnotationRepository
  ) {}

  async execute(input: CreateKnowledgeAnnotationInput): Promise<CreateKnowledgeAnnotationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.clsId();

    // All field names extracted from OpenAPI spec: annotation, linkedProposalId, materialPattern, promotedToPlaybook
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.materialPattern) {
      throw new ValidationError("materialPattern is required");
    }
    if (!input.annotation) {
      throw new ValidationError("annotation is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (classifications domain)
    const entityId = this.idGenerator.clsId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.knowledgeAnnotation.createKnowledgeAnnotation({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateKnowledgeAnnotationOutput;
  }
}
