/**
 * ExecuteGetKnowledgeAnnotation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetKnowledgeAnnotation Use Case
 *
 * DDD: Application use case for get KnowledgeAnnotation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetKnowledgeAnnotationInput, GetKnowledgeAnnotationOutput } from "../dto/knowledge-annotation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { KnowledgeAnnotationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetKnowledgeAnnotation {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly knowledgeAnnotation: KnowledgeAnnotationRepository
  ) {}

  async execute(input: GetKnowledgeAnnotationInput): Promise<GetKnowledgeAnnotationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.clsId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).annotationId) {
      throw new ValidationError("annotationId is required");
    }
    const annotationId = (input as any).annotationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.knowledgeAnnotation.getKnowledgeAnnotation({ annotationId: annotationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${annotationId}`);
    }

    return entity as GetKnowledgeAnnotationOutput;
  }
}
