/**
 * ExecuteCreateClassificationProposal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: classifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateClassificationProposal Use Case
 *
 * DDD: Application use case for create ClassificationProposal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateClassificationProposalInput, CreateClassificationProposalOutput } from "../dto/classification-proposal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { ClassificationProposalRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateClassificationProposal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly classificationProposal: ClassificationProposalRepository
  ) {}

  async execute(input: CreateClassificationProposalInput): Promise<CreateClassificationProposalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.clsId();

    // All field names extracted from OpenAPI spec: confidence, materialDescription, materialNumber, proposedEccn, proposedHsCode, rationale
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.materialDescription) {
      throw new ValidationError("materialDescription is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (classifications domain)
    const entityId = this.idGenerator.clsId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.classificationProposal.createClassificationProposal({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateClassificationProposalOutput;
  }
}
