/**
 * Report DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: metrics
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Report DTOs
 *
 * DDD: Application DTOs for Report use cases.
 */

import type { CycleTimeReportCreateRequest, GetCycleTimeReportParams, ListCycleTimeReportsParams } from "@phytoseal/core/metrics/types";

export type ListCycleTimeReportsInput = ListCycleTimeReportsParams;

export type CreateCycleTimeReportInput = CycleTimeReportCreateRequest;

export type GetCycleTimeReportInput = GetCycleTimeReportParams;

export type ListCycleTimeReportsOutput = {};

export type CreateCycleTimeReportOutput = {};

export type GetCycleTimeReportOutput = {};
