/**
 * ExecuteGetCertificate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetCertificate Use Case
 *
 * DDD: Application use case for get Certificate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetCertificateInput, GetCertificateOutput } from "../dto/certificate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { CertificateRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetCertificate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly certificate: CertificateRepository
  ) {}

  async execute(input: GetCertificateInput): Promise<GetCertificateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.crtId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).certificateId) {
      throw new ValidationError("certificateId is required");
    }
    const certificateId = (input as any).certificateId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.certificate.getCertificate({ certificateId: certificateId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${certificateId}`);
    }

    return entity as GetCertificateOutput;
  }
}
