/**
 * ExecuteListCertificateEvents - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListCertificateEvents Use Case
 *
 * DDD: Application use case for list Event.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListCertificateEventsInput, ListCertificateEventsOutput } from "../dto/event.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { EventRepository } from "../ports";

export class ExecuteListCertificateEvents {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly event: EventRepository
  ) {}

  async execute(input: ListCertificateEventsInput): Promise<ListCertificateEventsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.crtId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.event.listCertificateEvents({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListCertificateEventsOutput;
  }
}
