/**
 * ExecuteCreateCertificate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certificates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateCertificate Use Case
 *
 * DDD: Application use case for create Certificate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateCertificateInput, CreateCertificateOutput } from "../dto/certificate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@phytoseal/services/_shared/index.js";
import type { CertificateRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateCertificate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly certificate: CertificateRepository
  ) {}

  async execute(input: CreateCertificateInput): Promise<CreateCertificateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.crtId();

    // All field names extracted from OpenAPI spec: certificateType, exportAuthorityId, importAuthorityId, payloadHash, shipmentRef, status
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.certificateType) {
      throw new ValidationError("certificateType is required");
    }
    if (!input.exportAuthorityId) {
      throw new ValidationError("exportAuthorityId is required");
    }
    if (!input.payloadHash) {
      throw new ValidationError("payloadHash is required");
    }
    if (!input.shipmentRef) {
      throw new ValidationError("shipmentRef is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (certificates domain)
    const entityId = this.idGenerator.crtId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.certificate.createCertificate({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateCertificateOutput;
  }
}
